// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY4rp0WnPRJGsCpdA1jBL5iBdYWLKgaTk',
    appId: '1:12624666742:web:25572ffb0f8661456abf57',
    messagingSenderId: '12624666742',
    projectId: 'smart-hub-flutter',
    authDomain: 'smart-hub-flutter.firebaseapp.com',
    storageBucket: 'smart-hub-flutter.appspot.com',
    measurementId: 'G-S0KP122YYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQLqd0OVruR5oL32kP-bE6fQ8mRybQfmM',
    appId: '1:12624666742:android:ade65b9c516f8a896abf57',
    messagingSenderId: '12624666742',
    projectId: 'smart-hub-flutter',
    storageBucket: 'smart-hub-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoLKQHUuP7MxuamFZU7yNrm_18cl9qrdI',
    appId: '1:12624666742:ios:73301db0d2818e406abf57',
    messagingSenderId: '12624666742',
    projectId: 'smart-hub-flutter',
    storageBucket: 'smart-hub-flutter.appspot.com',
    iosBundleId: 'com.example.smartHubFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoLKQHUuP7MxuamFZU7yNrm_18cl9qrdI',
    appId: '1:12624666742:ios:89571579dc281d436abf57',
    messagingSenderId: '12624666742',
    projectId: 'smart-hub-flutter',
    storageBucket: 'smart-hub-flutter.appspot.com',
    iosBundleId: 'com.example.smartHubFlutter.RunnerTests',
  );
}
